# install pip.yml et Proxmoxer
# ansible-playbook ansible/Setup_Proxmox.yaml -i ansible/host -u root
---
- hosts: proxmox

- name: 'prep proxmox hosts for automation'
  hosts: 'proxmox'
  gather_facts: false
  vars:
    packages:
      - 'python3-pip'
      - 'python-dev'
      - 'build-essential'

  tasks:
    - name: 'install python-apt so native apt plugins work'
      package:
        name: 'python-apt'
        state: 'present'
    - name: 'switch to community repos'
      apt_repository:
        repo: 'deb https://enterprise.proxmox.com/debian/pve stretch pve-enterprise'
        state: 'absent'
      apt_repository:
        repo: 'deb http://download.proxmox.com/debian/pve stretch pve-no-subscription'
        state: 'present'
    - name: 'Update all packages to the latest version'
      apt:
        upgrade: 'dist'
    - name: 'Install pip packages'
      apt:
        name: "{{ packages }}"
    - name: 'pip update pip'
      pip:
        name: 'pip'
        state: 'latest'
    - name: 'Install dependencies'
      pip:
        name: 'virtualenv'
        state: 'latest'
      pip:
        name: 'proxmoxer'
        state: 'latest'

